name 'chef_auto_accumulator'
maintainer 'Ben Hughes'
maintainer_email 'bmhughes@bmhughes.co.uk'
license 'Apache-2.0'
description 'Installs/Configures chef_auto_accumulator'
source_url 'https://github.com/bmhughes/chef_auto_accumulator'
issues_url 'https://github.com/bmhughes/chef_auto_accumulator/issues'
chef_version '>= 16.0'
version '0.1.0'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'
