name 'chef_auto_accumulator'
maintainer 'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license 'Apache-2.0'
description 'Installs/Configures chef_auto_accumulator'
source_url 'https://github.com/sous-chefs/chef_auto_accumulator'
issues_url 'https://github.com/sous-chefs/chef_auto_accumulator/issues'
chef_version '>= 16.0'
version '0.6.0'

supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'ubuntu'

gem 'deepsort', '~> 0.5'
gem 'inifile', '~> 3.0'
gem 'toml-rb', '~> 2.2'
